// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: meridian.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "meridian";

export interface EmptyRequest {
}

/** Sub-message representing department details */
export interface DepartmentResponse {
  id: number;
  name: string;
}

/** Sub-message representing the weekly hybrid work distribution */
export interface HybridScheduleResponse {
  monday: boolean;
  tuesday: boolean;
  wednesday: boolean;
  thursday: boolean;
  friday: boolean;
}

/** Main employee message containing composition links to department and schedule */
export interface EmployeeResponse {
  id: number;
  firstName: string;
  lastName: string;
  slackHandle: string;
  hireDate: string;
  department: DepartmentResponse | undefined;
  hybridSchedule: HybridScheduleResponse | undefined;
}

export interface EmployeeListResponse {
  employees: EmployeeResponse[];
}

function createBaseEmptyRequest(): EmptyRequest {
  return {};
}

export const EmptyRequest: MessageFns<EmptyRequest> = {
  encode(_: EmptyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmptyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmptyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): EmptyRequest {
    return {};
  },

  toJSON(_: EmptyRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<EmptyRequest>, I>>(base?: I): EmptyRequest {
    return EmptyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmptyRequest>, I>>(_: I): EmptyRequest {
    const message = createBaseEmptyRequest();
    return message;
  },
};

function createBaseDepartmentResponse(): DepartmentResponse {
  return { id: 0, name: "" };
}

export const DepartmentResponse: MessageFns<DepartmentResponse> = {
  encode(message: DepartmentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DepartmentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDepartmentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DepartmentResponse {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: DepartmentResponse): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DepartmentResponse>, I>>(base?: I): DepartmentResponse {
    return DepartmentResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DepartmentResponse>, I>>(object: I): DepartmentResponse {
    const message = createBaseDepartmentResponse();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseHybridScheduleResponse(): HybridScheduleResponse {
  return { monday: false, tuesday: false, wednesday: false, thursday: false, friday: false };
}

export const HybridScheduleResponse: MessageFns<HybridScheduleResponse> = {
  encode(message: HybridScheduleResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.monday !== false) {
      writer.uint32(8).bool(message.monday);
    }
    if (message.tuesday !== false) {
      writer.uint32(16).bool(message.tuesday);
    }
    if (message.wednesday !== false) {
      writer.uint32(24).bool(message.wednesday);
    }
    if (message.thursday !== false) {
      writer.uint32(32).bool(message.thursday);
    }
    if (message.friday !== false) {
      writer.uint32(40).bool(message.friday);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HybridScheduleResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHybridScheduleResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.monday = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.tuesday = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.wednesday = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.thursday = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.friday = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HybridScheduleResponse {
    return {
      monday: isSet(object.monday) ? globalThis.Boolean(object.monday) : false,
      tuesday: isSet(object.tuesday) ? globalThis.Boolean(object.tuesday) : false,
      wednesday: isSet(object.wednesday) ? globalThis.Boolean(object.wednesday) : false,
      thursday: isSet(object.thursday) ? globalThis.Boolean(object.thursday) : false,
      friday: isSet(object.friday) ? globalThis.Boolean(object.friday) : false,
    };
  },

  toJSON(message: HybridScheduleResponse): unknown {
    const obj: any = {};
    if (message.monday !== false) {
      obj.monday = message.monday;
    }
    if (message.tuesday !== false) {
      obj.tuesday = message.tuesday;
    }
    if (message.wednesday !== false) {
      obj.wednesday = message.wednesday;
    }
    if (message.thursday !== false) {
      obj.thursday = message.thursday;
    }
    if (message.friday !== false) {
      obj.friday = message.friday;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HybridScheduleResponse>, I>>(base?: I): HybridScheduleResponse {
    return HybridScheduleResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HybridScheduleResponse>, I>>(object: I): HybridScheduleResponse {
    const message = createBaseHybridScheduleResponse();
    message.monday = object.monday ?? false;
    message.tuesday = object.tuesday ?? false;
    message.wednesday = object.wednesday ?? false;
    message.thursday = object.thursday ?? false;
    message.friday = object.friday ?? false;
    return message;
  },
};

function createBaseEmployeeResponse(): EmployeeResponse {
  return {
    id: 0,
    firstName: "",
    lastName: "",
    slackHandle: "",
    hireDate: "",
    department: undefined,
    hybridSchedule: undefined,
  };
}

export const EmployeeResponse: MessageFns<EmployeeResponse> = {
  encode(message: EmployeeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.firstName !== "") {
      writer.uint32(18).string(message.firstName);
    }
    if (message.lastName !== "") {
      writer.uint32(26).string(message.lastName);
    }
    if (message.slackHandle !== "") {
      writer.uint32(34).string(message.slackHandle);
    }
    if (message.hireDate !== "") {
      writer.uint32(42).string(message.hireDate);
    }
    if (message.department !== undefined) {
      DepartmentResponse.encode(message.department, writer.uint32(50).fork()).join();
    }
    if (message.hybridSchedule !== undefined) {
      HybridScheduleResponse.encode(message.hybridSchedule, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmployeeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmployeeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.firstName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.lastName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.slackHandle = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.hireDate = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.department = DepartmentResponse.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.hybridSchedule = HybridScheduleResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmployeeResponse {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      firstName: isSet(object.firstName)
        ? globalThis.String(object.firstName)
        : isSet(object.first_name)
        ? globalThis.String(object.first_name)
        : "",
      lastName: isSet(object.lastName)
        ? globalThis.String(object.lastName)
        : isSet(object.last_name)
        ? globalThis.String(object.last_name)
        : "",
      slackHandle: isSet(object.slackHandle)
        ? globalThis.String(object.slackHandle)
        : isSet(object.slack_handle)
        ? globalThis.String(object.slack_handle)
        : "",
      hireDate: isSet(object.hireDate)
        ? globalThis.String(object.hireDate)
        : isSet(object.hire_date)
        ? globalThis.String(object.hire_date)
        : "",
      department: isSet(object.department) ? DepartmentResponse.fromJSON(object.department) : undefined,
      hybridSchedule: isSet(object.hybridSchedule)
        ? HybridScheduleResponse.fromJSON(object.hybridSchedule)
        : isSet(object.hybrid_schedule)
        ? HybridScheduleResponse.fromJSON(object.hybrid_schedule)
        : undefined,
    };
  },

  toJSON(message: EmployeeResponse): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.firstName !== "") {
      obj.firstName = message.firstName;
    }
    if (message.lastName !== "") {
      obj.lastName = message.lastName;
    }
    if (message.slackHandle !== "") {
      obj.slackHandle = message.slackHandle;
    }
    if (message.hireDate !== "") {
      obj.hireDate = message.hireDate;
    }
    if (message.department !== undefined) {
      obj.department = DepartmentResponse.toJSON(message.department);
    }
    if (message.hybridSchedule !== undefined) {
      obj.hybridSchedule = HybridScheduleResponse.toJSON(message.hybridSchedule);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmployeeResponse>, I>>(base?: I): EmployeeResponse {
    return EmployeeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmployeeResponse>, I>>(object: I): EmployeeResponse {
    const message = createBaseEmployeeResponse();
    message.id = object.id ?? 0;
    message.firstName = object.firstName ?? "";
    message.lastName = object.lastName ?? "";
    message.slackHandle = object.slackHandle ?? "";
    message.hireDate = object.hireDate ?? "";
    message.department = (object.department !== undefined && object.department !== null)
      ? DepartmentResponse.fromPartial(object.department)
      : undefined;
    message.hybridSchedule = (object.hybridSchedule !== undefined && object.hybridSchedule !== null)
      ? HybridScheduleResponse.fromPartial(object.hybridSchedule)
      : undefined;
    return message;
  },
};

function createBaseEmployeeListResponse(): EmployeeListResponse {
  return { employees: [] };
}

export const EmployeeListResponse: MessageFns<EmployeeListResponse> = {
  encode(message: EmployeeListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.employees) {
      EmployeeResponse.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmployeeListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmployeeListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.employees.push(EmployeeResponse.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmployeeListResponse {
    return {
      employees: globalThis.Array.isArray(object?.employees)
        ? object.employees.map((e: any) => EmployeeResponse.fromJSON(e))
        : [],
    };
  },

  toJSON(message: EmployeeListResponse): unknown {
    const obj: any = {};
    if (message.employees?.length) {
      obj.employees = message.employees.map((e) => EmployeeResponse.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmployeeListResponse>, I>>(base?: I): EmployeeListResponse {
    return EmployeeListResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmployeeListResponse>, I>>(object: I): EmployeeListResponse {
    const message = createBaseEmployeeListResponse();
    message.employees = object.employees?.map((e) => EmployeeResponse.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
